export const outreachTargetPolicyVersion = "outreach-target-policy.v2";

// Platform accounts, marketplace listings and corporate product sites are not
// publisher outreach inventory. Rank or a backlink to a competitor is not an
// exception. A future placement-specific product needs its own verified path.
export const nonOutreachTargetDomains = Object.freeze([
  "amazon.com",
  "amazon.co.uk",
  "amazon.ca",
  "amazon.de",
  "amazon.fr",
  "amazon.it",
  "amazon.es",
  "amazon.co.jp",
  "amazon.in",
  "amazon.com.au",
  "amazon.com.br",
  "amazon.com.mx",
  "amazon.nl",
  "amazon.se",
  "amazon.pl",
  "amazon.sg",
  "amazon.ae",
  "amazon.sa",
  "amazon.com.tr",
  "amazon.co.za",
  "apple.com",
  "icloud.com",
  "microsoft.com",
  "windows.com",
  "office.com",
  "azure.com",
  "live.com",
  "outlook.com",
  "google.com",
  "android.com",
  "android.org",
  "google.co.uk",
  "google.de",
  "google.fr",
  "google.co.jp",
  "google.co.in",
  "google.com.au",
  "google.ca",
  "google.com.br",
  "google.co.za",
  "chromium.org",
  "chrome.com",
  "googleblog.com",
  "blog.google",
  "about.google",
  "abc.xyz",
  "amazonaws.com",
  "amazon.jobs",
  "aboutamazon.com",
  "primevideo.com",
  "twitch.tv",
  "audible.com",
  "samsung.com",
  "huawei.com",
  "mi.com",
  "xiaomi.com",
  "sony.com",
  "intel.com",
  "amd.com",
  "nvidia.com",
  "ibm.com",
  "oracle.com",
  "adobe.com",
  "salesforce.com",
  "cisco.com",
  "dell.com",
  "hp.com",
  "lenovo.com",
  "qualcomm.com",
  "tesla.com",
  "netflix.com",
  "spotify.com",
  "paypal.com",
  "visa.com",
  "mastercard.com",
  "bing.com",
  "yahoo.com",
  "duckduckgo.com",
  "baidu.com",
  "reddit.com",
  "facebook.com",
  "meta.com",
  "whatsapp.com",
  "instagram.com",
  "linkedin.com",
  "pinterest.com",
  "tiktok.com",
  "twitter.com",
  "x.com",
  "youtube.com",
  "youtu.be",
  "threads.net",
  "threads.com",
  "quora.com",
  "github.com",
  "wikipedia.org",
  "wikimedia.org",
  "ebay.com",
  "ebay.co.uk",
  "aliexpress.com",
  "alibaba.com",
  "etsy.com",
  "walmart.com",
  "temu.com",
  "target.com",
  "bestbuy.com",
  "taobao.com",
  "tmall.com",
  "jd.com",
  "rakuten.com",
  "rakuten.co.jp",
]);

export function excludedOutreachTarget(domain: string): Readonly<{
  policyVersion: typeof outreachTargetPolicyVersion;
  reason: "NON_OUTREACH_TARGET";
  matchedDomain: string;
}> | null {
  const normalized = domain.trim().toLowerCase().replace(/\.$/u, "");
  const matchedDomain = nonOutreachTargetDomains.find(
    (blocked) => normalized === blocked || normalized.endsWith(`.${blocked}`),
  );
  return matchedDomain === undefined
    ? null
    : Object.freeze({
        policyVersion: outreachTargetPolicyVersion,
        reason: "NON_OUTREACH_TARGET",
        matchedDomain,
      });
}
